// Comprehensive list of countries for international checkout with flag emojis and dial codes

function getFlagEmoji(countryCode) {
  if (!countryCode || countryCode.length !== 2) return "🌐";
  const codePoints = countryCode
    .toUpperCase()
    .split("")
    .map((char) => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}

import { getCurrencyForCountry } from "./currency";

export const ALL_COUNTRIES = [
  { code: "ZA", name: "South Africa", phone: "+27" },
  { code: "US", name: "United States", phone: "+1" },
  { code: "GB", name: "United Kingdom", phone: "+44" },
  { code: "CA", name: "Canada", phone: "+1" },
  { code: "AU", name: "Australia", phone: "+61" },
  { code: "DE", name: "Germany", phone: "+49" },
  { code: "FR", name: "France", phone: "+33" },
  { code: "AE", name: "United Arab Emirates", phone: "+971" },
  { code: "NG", name: "Nigeria", phone: "+234" },
  { code: "KE", name: "Kenya", phone: "+254" },
  { code: "AF", name: "Afghanistan", phone: "+93" },
  { code: "AL", name: "Albania", phone: "+355" },
  { code: "DZ", name: "Algeria", phone: "+213" },
  { code: "AD", name: "Andorra", phone: "+376" },
  { code: "AO", name: "Angola", phone: "+244" },
  { code: "AG", name: "Antigua and Barbuda", phone: "+1-268" },
  { code: "AR", name: "Argentina", phone: "+54" },
  { code: "AM", name: "Armenia", phone: "+374" },
  { code: "AT", name: "Austria", phone: "+43" },
  { code: "AZ", name: "Azerbaijan", phone: "+994" },
  { code: "BS", name: "Bahamas", phone: "+1-242" },
  { code: "BH", name: "Bahrain", phone: "+973" },
  { code: "BD", name: "Bangladesh", phone: "+880" },
  { code: "BB", name: "Barbados", phone: "+1-246" },
  { code: "BY", name: "Belarus", phone: "+375" },
  { code: "BE", name: "Belgium", phone: "+32" },
  { code: "BZ", name: "Belize", phone: "+501" },
  { code: "BJ", name: "Benin", phone: "+229" },
  { code: "BT", name: "Bhutan", phone: "+975" },
  { code: "BO", name: "Bolivia", phone: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", phone: "+387" },
  { code: "BW", name: "Botswana", phone: "+267" },
  { code: "BR", name: "Brazil", phone: "+55" },
  { code: "BN", name: "Brunei", phone: "+673" },
  { code: "BG", name: "Bulgaria", phone: "+359" },
  { code: "BF", name: "Burkina Faso", phone: "+226" },
  { code: "BI", name: "Burundi", phone: "+257" },
  { code: "KH", name: "Cambodia", phone: "+855" },
  { code: "CM", name: "Cameroon", phone: "+237" },
  { code: "CV", name: "Cape Verde", phone: "+238" },
  { code: "CF", name: "Central African Republic", phone: "+236" },
  { code: "TD", name: "Chad", phone: "+235" },
  { code: "CL", name: "Chile", phone: "+56" },
  { code: "CN", name: "China", phone: "+86" },
  { code: "CO", name: "Colombia", phone: "+57" },
  { code: "KM", name: "Comoros", phone: "+269" },
  { code: "CG", name: "Congo - Brazzaville", phone: "+242" },
  { code: "CD", name: "Congo - Kinshasa", phone: "+243" },
  { code: "CR", name: "Costa Rica", phone: "+506" },
  { code: "HR", name: "Croatia", phone: "+385" },
  { code: "CU", name: "Cuba", phone: "+53" },
  { code: "CY", name: "Cyprus", phone: "+357" },
  { code: "CZ", name: "Czech Republic", phone: "+420" },
  { code: "DK", name: "Denmark", phone: "+45" },
  { code: "DJ", name: "Djibouti", phone: "+253" },
  { code: "DM", name: "Dominica", phone: "+1-767" },
  { code: "DO", name: "Dominican Republic", phone: "+1-809" },
  { code: "EC", name: "Ecuador", phone: "+593" },
  { code: "EG", name: "Egypt", phone: "+20" },
  { code: "SV", name: "El Salvador", phone: "+503" },
  { code: "GQ", name: "Equatorial Guinea", phone: "+240" },
  { code: "ER", name: "Eritrea", phone: "+291" },
  { code: "EE", name: "Estonia", phone: "+372" },
  { code: "SZ", name: "Eswatini (Swaziland)", phone: "+268" },
  { code: "ET", name: "Ethiopia", phone: "+251" },
  { code: "FJ", name: "Fiji", phone: "+679" },
  { code: "FI", name: "Finland", phone: "+358" },
  { code: "GA", name: "Gabon", phone: "+241" },
  { code: "GM", name: "Gambia", phone: "+220" },
  { code: "GE", name: "Georgia", phone: "+995" },
  { code: "GH", name: "Ghana", phone: "+233" },
  { code: "GR", name: "Greece", phone: "+30" },
  { code: "GD", name: "Grenada", phone: "+1-473" },
  { code: "GT", name: "Guatemala", phone: "+502" },
  { code: "GN", name: "Guinea", phone: "+224" },
  { code: "GW", name: "Guinea-Bissau", phone: "+245" },
  { code: "GY", name: "Guyana", phone: "+592" },
  { code: "HT", name: "Haiti", phone: "+509" },
  { code: "HN", name: "Honduras", phone: "+504" },
  { code: "HK", name: "Hong Kong SAR China", phone: "+852" },
  { code: "HU", name: "Hungary", phone: "+36" },
  { code: "IS", name: "Iceland", phone: "+354" },
  { code: "IN", name: "India", phone: "+91" },
  { code: "ID", name: "Indonesia", phone: "+62" },
  { code: "IR", name: "Iran", phone: "+98" },
  { code: "IQ", name: "Iraq", phone: "+964" },
  { code: "IE", name: "Ireland", phone: "+353" },
  { code: "IL", name: "Israel", phone: "+972" },
  { code: "IT", name: "Italy", phone: "+39" },
  { code: "CI", name: "Ivory Coast (Côte d'Ivoire)", phone: "+225" },
  { code: "JM", name: "Jamaica", phone: "+1-876" },
  { code: "JP", name: "Japan", phone: "+81" },
  { code: "JO", name: "Jordan", phone: "+962" },
  { code: "KZ", name: "Kazakhstan", phone: "+7" },
  { code: "KW", name: "Kuwait", phone: "+965" },
  { code: "KG", name: "Kyrgyzstan", phone: "+996" },
  { code: "LA", name: "Laos", phone: "+856" },
  { code: "LV", name: "Latvia", phone: "+371" },
  { code: "LB", name: "Lebanon", phone: "+961" },
  { code: "LS", name: "Lesotho", phone: "+266" },
  { code: "LR", name: "Liberia", phone: "+231" },
  { code: "LY", name: "Libya", phone: "+218" },
  { code: "LI", name: "Liechtenstein", phone: "+423" },
  { code: "LT", name: "Lithuania", phone: "+370" },
  { code: "LU", name: "Luxembourg", phone: "+352" },
  { code: "MO", name: "Macao SAR China", phone: "+853" },
  { code: "MG", name: "Madagascar", phone: "+261" },
  { code: "MW", name: "Malawi", phone: "+265" },
  { code: "MY", name: "Malaysia", phone: "+60" },
  { code: "MV", name: "Maldives", phone: "+960" },
  { code: "ML", name: "Mali", phone: "+223" },
  { code: "MT", name: "Malta", phone: "+356" },
  { code: "MR", name: "Mauritania", phone: "+222" },
  { code: "MU", name: "Mauritius", phone: "+230" },
  { code: "MX", name: "Mexico", phone: "+52" },
  { code: "MD", name: "Moldova", phone: "+373" },
  { code: "MC", name: "Monaco", phone: "+377" },
  { code: "MN", name: "Mongolia", phone: "+976" },
  { code: "ME", name: "Montenegro", phone: "+382" },
  { code: "MA", name: "Morocco", phone: "+212" },
  { code: "MZ", name: "Mozambique", phone: "+258" },
  { code: "MM", name: "Myanmar (Burma)", phone: "+95" },
  { code: "NA", name: "Namibia", phone: "+264" },
  { code: "NP", name: "Nepal", phone: "+977" },
  { code: "NL", name: "Netherlands", phone: "+31" },
  { code: "NZ", name: "New Zealand", phone: "+64" },
  { code: "NI", name: "Nicaragua", phone: "+505" },
  { code: "NE", name: "Niger", phone: "+227" },
  { code: "KP", name: "North Korea", phone: "+850" },
  { code: "MK", name: "North Macedonia", phone: "+389" },
  { code: "NO", name: "Norway", phone: "+47" },
  { code: "OM", name: "Oman", phone: "+968" },
  { code: "PK", name: "Pakistan", phone: "+92" },
  { code: "PS", name: "Palestinian Territories", phone: "+970" },
  { code: "PA", name: "Panama", phone: "+507" },
  { code: "PG", name: "Papua New Guinea", phone: "+675" },
  { code: "PY", name: "Paraguay", phone: "+595" },
  { code: "PE", name: "Peru", phone: "+51" },
  { code: "PH", name: "Philippines", phone: "+63" },
  { code: "PL", name: "Poland", phone: "+48" },
  { code: "PT", name: "Portugal", phone: "+351" },
  { code: "QA", name: "Qatar", phone: "+974" },
  { code: "RO", name: "Romania", phone: "+40" },
  { code: "RU", name: "Russia", phone: "+7" },
  { code: "RW", name: "Rwanda", phone: "+250" },
  { code: "KN", name: "Saint Kitts and Nevis", phone: "+1-869" },
  { code: "LC", name: "Saint Lucia", phone: "+1-758" },
  { code: "VC", name: "Saint Vincent and the Grenadines", phone: "+1-784" },
  { code: "WS", name: "Samoa", phone: "+685" },
  { code: "SM", name: "San Marino", phone: "+378" },
  { code: "ST", name: "São Tomé and Príncipe", phone: "+239" },
  { code: "SA", name: "Saudi Arabia", phone: "+966" },
  { code: "SN", name: "Senegal", phone: "+221" },
  { code: "RS", name: "Serbia", phone: "+381" },
  { code: "SC", name: "Seychelles", phone: "+248" },
  { code: "SL", name: "Sierra Leone", phone: "+232" },
  { code: "SG", name: "Singapore", phone: "+65" },
  { code: "SK", name: "Slovakia", phone: "+421" },
  { code: "SI", name: "Slovenia", phone: "+386" },
  { code: "SB", name: "Solomon Islands", phone: "+677" },
  { code: "SO", name: "Somalia", phone: "+252" },
  { code: "KR", name: "South Korea", phone: "+82" },
  { code: "SS", name: "South Sudan", phone: "+211" },
  { code: "ES", name: "Spain", phone: "+34" },
  { code: "LK", name: "Sri Lanka", phone: "+94" },
  { code: "SD", name: "Sudan", phone: "+249" },
  { code: "SR", name: "Suriname", phone: "+597" },
  { code: "SE", name: "Sweden", phone: "+46" },
  { code: "CH", name: "Switzerland", phone: "+41" },
  { code: "SY", name: "Syria", phone: "+963" },
  { code: "TW", name: "Taiwan", phone: "+886" },
  { code: "TJ", name: "Tajikistan", phone: "+992" },
  { code: "TZ", name: "Tanzania", phone: "+255" },
  { code: "TH", name: "Thailand", phone: "+66" },
  { code: "TL", name: "Timor-Leste", phone: "+670" },
  { code: "TG", name: "Togo", phone: "+228" },
  { code: "TO", name: "Tonga", phone: "+676" },
  { code: "TT", name: "Trinidad and Tobago", phone: "+1-868" },
  { code: "TN", name: "Tunisia", phone: "+216" },
  { code: "TR", name: "Turkey", phone: "+90" },
  { code: "TM", name: "Turkmenistan", phone: "+993" },
  { code: "TV", name: "Tuvalu", phone: "+688" },
  { code: "UG", name: "Uganda", phone: "+256" },
  { code: "UA", name: "Ukraine", phone: "+380" },
  { code: "UY", name: "Uruguay", phone: "+598" },
  { code: "UZ", name: "Uzbekistan", phone: "+998" },
  { code: "VU", name: "Vanuatu", phone: "+678" },
  { code: "VA", name: "Vatican City", phone: "+39-06" },
  { code: "VE", name: "Venezuela", phone: "+58" },
  { code: "VN", name: "Vietnam", phone: "+84" },
  { code: "YE", name: "Yemen", phone: "+967" },
  { code: "ZM", name: "Zambia", phone: "+260" },
  { code: "ZW", name: "Zimbabwe", phone: "+263" }
].map((c) => ({
  ...c,
  flag: getFlagEmoji(c.code),
  currency: getCurrencyForCountry(c.code)
}));

export function getCountryByCode(code) {
  return ALL_COUNTRIES.find((c) => c.code === code) || ALL_COUNTRIES[0];
}

export function getCountryByName(name) {
  return ALL_COUNTRIES.find((c) => c.name.toLowerCase() === (name || "").toLowerCase()) || ALL_COUNTRIES[0];
}
